name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: npm install
        run: |
          ls
          npm install
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: npm test
        run: |
          ls
          npm test