name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14

    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{env.NODE_VERSION}}

        - name: NODE_VERSION
          run: |
            node -v
            echo "The actualy version of node is ${{env.NODE_VERSION}}" # This will output '14'ut 'green'