name: npm test Matrix
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    needs: run-npm-install
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: [14, lts]
        include:
          - os: ubuntu-latest
            node: 12
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.version }}
        - uses: actions/cache@v3
          with:
            path: ./node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        - name: run test
          shell: bash
          run: |
            npm install

  run-npm-test:
    needs: run-npm-test
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: [14, lts]
        include:
          - os: ubuntu-latest
            node: 12
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.version }}
        - uses: actions/cache@v3
          with:
            path: ./node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        - name: run test
          shell: bash
          run: |
            npm test