name: npm test cache
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: run install
          shell: bash
          run: |
            npm install
        - name: Cache multiple paths
          uses: actions/cache@v3
          with:
            path: |
              node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  run-npm-test:
    needs: run-npm-install
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: run test
          shell: bash
          run: |
            npm test