name: reusable workflow
on: 
  workflow_dispatch: 
 
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/workflows/ex4.yaml
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.envPAT }}