name: reusable workflow of ex4.yaml
on: 
  workflow_dispatch: 
 
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ex4
        with:
          node-version: 14